import type { ConstraintId, FlightOfferId, TravellerId } from "./ids";
import type { IsoDateTime } from "./time";

/**
 * The output of the deterministic feasibility engine.
 *
 * Principle 9: no model participates in producing any of this. Every field is
 * computed by pure functions over constraints and normalised offers. Where a
 * value cannot be computed it is reported as an unknown, never guessed, which is
 * why unknowns is a first-class list rather than an empty case.
 */

/** The unit a magnitude is measured in, so a number is never ambiguous. */
export type MagnitudeUnit = "CURRENCY_MINOR" | "MINUTES" | "STOPS" | "COUNT" | "DAYS";

/** Why one constraint passed, failed, or could not be decided. */
export interface ConstraintOutcome {
  readonly constraintId: ConstraintId;
  readonly travellerId: TravellerId;
  /**
   * Plain-language account of the comparison actually performed, e.g.
   * "fare 452.00 SGD exceeds hard maximum 450.00 SGD by 2.00 SGD".
   * Generated by code from the comparison itself, so it cannot drift from truth.
   */
  readonly reason: string;
}

/**
 * A soft violation additionally records how badly the preference was missed,
 * because the compromise engine ranks relaxations by magnitude and needs a
 * number rather than a boolean.
 */
export interface SoftConstraintOutcome extends ConstraintOutcome {
  /** How far past the preference this offer sits. Always positive. */
  readonly magnitude: number;
  readonly unit: MagnitudeUnit;
}

/** Why the engine could not decide a constraint. */
export type UnknownReason =
  /** The offer lacked the data, e.g. the provider reported no baggage. */
  | "OFFER_DATA_MISSING"
  /** The constraint is prose a human must read. */
  | "CONSTRAINT_NOT_MACHINE_EVALUABLE"
  /** Consequential, model-proposed, and not yet confirmed by its owner. */
  | "CONSTRAINT_UNCONFIRMED"
  /** Amounts are in different currencies and no conversion is available. */
  | "CURRENCY_MISMATCH"
  /** The constraint itself is malformed, e.g. an empty allow-list. */
  | "CONSTRAINT_MALFORMED"
  /** Real and owned, but not decidable from a single offer in this phase. */
  | "DEFERRED_TO_LATER_PHASE";

export interface UnknownOutcome extends ConstraintOutcome {
  readonly unknownReason: UnknownReason;
}

/**
 * The worst thing found for one traveller against one offer.
 *
 * Precedence is HARD_VIOLATION > UNKNOWN > SOFT_VIOLATION > PASS. Unknown ranks
 * above a soft violation deliberately: a soft violation is a known cost that can
 * be traded, whereas an unknown is missing information that must be resolved
 * before anyone can judge the trade.
 */
export type TravellerVerdict = "PASS" | "SOFT_VIOLATION" | "UNKNOWN" | "HARD_VIOLATION";

/** One traveller's full result against one offer. */
export interface TravellerOfferFeasibility {
  readonly travellerId: TravellerId;
  readonly verdict: TravellerVerdict;
  readonly satisfied: readonly ConstraintOutcome[];
  readonly hardViolations: readonly ConstraintOutcome[];
  readonly softViolations: readonly SoftConstraintOutcome[];
  readonly unknowns: readonly UnknownOutcome[];
}

/**
 * One offer judged against the whole current travelling set.
 *
 * feasible is true only when no traveller has a hard violation. Unknowns do NOT
 * make an offer infeasible by themselves, but they set
 * hasUnresolvedInformation, so the product can ask the one question that would
 * settle them rather than silently assuming a pass.
 */
export interface OfferFeasibility {
  readonly offerId: FlightOfferId;
  readonly feasible: boolean;
  readonly hasUnresolvedInformation: boolean;

  readonly perTraveller: readonly TravellerOfferFeasibility[];

  readonly satisfiedConstraintIds: readonly ConstraintId[];
  readonly hardViolationConstraintIds: readonly ConstraintId[];
  readonly softViolationConstraintIds: readonly ConstraintId[];
  readonly unknownConstraintIds: readonly ConstraintId[];

  /** Travellers with at least one hard violation against this offer. */
  readonly blockedTravellerIds: readonly TravellerId[];

  /**
   * One line answering the question of why an offer is rejected, assembled from
   * the per-traveller verdicts.
   *
   * WARNING: this is DOMAIN output, not group-facing copy. It names travellers,
   * so rendering it unchanged to the whole group would attribute a block to a
   * person and breach Principle 8. It never quotes a constraint VALUE, but the
   * attribution alone is enough to require redaction before display. The
   * group-facing wording layer is a later phase.
   */
  readonly summary: string;
}

export interface FeasibilityReport {
  /** Passed in by the caller. The engine never reads the clock. */
  readonly evaluatedAt: IsoDateTime;
  readonly results: readonly OfferFeasibility[];
  /** Offer ids with no hard violation, in the order the offers were supplied. */
  readonly feasibleOfferIds: readonly FlightOfferId[];
}
